defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/fastwam@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - _self_
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "libero_spatial_eval_fastwam"
    logger_backends: ["tensorboard"]

  max_epochs: 1
  only_eval: true
  val_check_interval: -1
  save_interval: -1
  resume_dir: null
  ckpt_path: null

algorithm:
  normalize_advantages: true
  kl_penalty: kl
  group_size: 4
  rollout_epoch: 1
  eval_rollout_epoch: 1

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level

  update_epoch: 1
  adv_type: grpo
  loss_type: actor

  gamma: 0.99
  gae_lambda: 0.95
  bootstrap_type: always
  kl_beta: 0.0
  entropy_bonus: 0.0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

  sampling_params:
    do_sample: false
    temperature_train: 1.0
    temperature_eval: 0.0
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

env:
  group_name: "EnvGroup"

  train:
    total_num_envs: 8
    max_episode_steps: 400
    max_steps_per_rollout_epoch: 400
    group_size: 1

  eval:
    total_num_envs: 8
    auto_reset: true
    ignore_terminations: true
    max_episode_steps: 400
    max_steps_per_rollout_epoch: 400
    group_size: 1
    is_eval: true

    video_cfg:
      save_video: true
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  enable_offload: false
  pipeline_stage_num: 1

  model:
    model_path: ${actor.model.model_path}
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1
  global_batch_size: 8
  seed: 0
  enable_offload: false

  model:
    num_action_chunks: 10
    action_horizon: 32

  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: false
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: false

critic:
  use_critic_model: false
